Added framework to parse individual geolocation items. Added code to parse IP address

diff --git a/geoip b/geoip
--- a/geoip
+++ b/geoip
@@ -20,11 +20,12 @@ USAGE="Usage: geoip [OPTION] [IP Address]
 
 Options:
 -h, --help       Show help and usage information
--v, --version    Show version information"
+-v, --version    Show version information
+-r, --raw        Show raw output"
 
 # --- Dependecy Check ---
 command -v curl >/dev/null 2>&1 || { echo >&2 "[ERROR] Dependency curl not installed. Exiting."; exit 1; }
-
+command -v grep >/dev/null 2>&1 || { echo >&2 "[ERROR] Dependency grep not installed. Exiting."; exit 1; }
 
 # --- Arguments ---
 # Check that there is at least one argument. If not show usage.
@@ -37,6 +38,8 @@ if [ $# -eq 0 ]; then
 fi
 
 # Handle arguments
+RAWOUTPUT=1
+
 while [[ $# > 1 ]]
 do
     key="$1"
@@ -53,6 +56,9 @@ do
 	    echo "Version: $VERSION"
 	    exit 0
 	    ;;
+	-r|--raw)
+	   RAWOUTPUT=0
+	   ;;
 	*)
 	    echo "Unknown argument: $key"
 	    exit 1
@@ -74,6 +80,37 @@ if [ $? -ne 0 ]; then
     exit 1
 fi
 
-echo "$GEODATA"
+# Display raw output
+if [ $RAWOUTPUT -eq 0 ]; then
+    echo "$GEODATA"
+    exit 0
+fi
+
+# TODO: Message "Please provied a valid IP address" can be returned while curl still returns 0
+# TODO: Make sure that returned data is valid JSON. Can probably happen while being parsed
+
+# IP Address
+IP=`echo "$GEODATA" | grep -o '"ip":\s"[^\s"]*"' | grep -o '\d\{1,3\}\.\d\{1,3\}\.\d\{1,3\}\.\d\{1,3\}'`
+
+# Hostname
+HOST=
+
+# City
+CITY=
+
+# Region
+REGION=
+
+# Country
+COUNTRY=
+
+# Location
+LOCATION=
+
+# Organization
+ORGANIZATION=
+
+# Postal Code
+POSTAL=
 
 exit 0
